version: '3'

services:
  app:
    image: jenkins/jenkins:{{ pillar.jenkins.version }}
    ports:
      - {{ pillar.static.proxy_ports.jenkins_http }}:8080
      - {{ pillar.static.proxy_ports.jenkins_agent }}:{{ pillar.static.proxy_ports.jenkins_agent }}
    volumes:
      - {{ pillar.jenkins.data_dir }}:/var/jenkins_home
    restart: always
