#!/bin/bash

# This script calls remote host from fish

SSH_CONN=$1

# Cut hostname before 1st dot
SSH_HOSTNAME=$(echo "${SSH_CONN}" | cut -d '@' -f 2 | cut -d '.' -f 1)

# Cut username (if exists)
if grep -q "@" <<< "$SSH_CONN"; then
    SSH_USERNAME=$(echo "${SSH_CONN}" | cut -d '@' -f 1)
else
    SSH_USERNAME=root
fi

if [[ -z "${SSH_USERNAME}" ]]; then
    echo "Invalid SSH user@host!"
    exit 1
fi

# echo "${SSH_USERNAME}, ${SSH_HOSTNAME}"

# Fake konsole tab title: create and cd to "host"
FAKE_NAME="(${SSH_USERNAME}) ${SSH_HOSTNAME}"
FAKE_PATH=/tmp/fssh-fake-path/"${FAKE_NAME}"
mkdir -p "${FAKE_PATH}"
cd "${FAKE_PATH}"

# Remove fake folder on exit
function finish {
    rm -rf "${FAKE_PATH}"
}
trap finish EXIT

# Call SSH
ssh ${SSH_USERNAME}@${SSH_HOSTNAME} -t fish
