#!/usr/bin/env python3

import datetime
import sys

x = datetime.datetime.now()

hour = int(x.strftime('%H'))
wday = int(x.strftime('%w'))

if (
    (hour >= 6 and hour <= 18)
    and (wday >= 1 and wday <= 5)
):
    print('yes')
    sys.exit(0)
else:
    print('no')
    sys.exit(1)
