# Samba server
version: '3'

services:
  samba:
    build: .
    container_name: {{ pillar.samba.id }}
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
      - /run/samba
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/group:/etc/group:ro
      - {{ pillar.samba.data_dir }}/etc:/etc/samba:ro
      - {{ pillar.samba.data_dir }}/lib:/var/lib/samba
      - /srv/share:/srv/share
