# Openhab
version: '2'

services:
  openhab:
    image: openhab/openhab:{{ pillar.openhab.version }}
    restart: always
    ports:
      - 8080:8080
    environment:
      - USER_ID={{ pillar.uids.master }}
      - GROUP_ID={{ pillar.uids.master }}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /opt/openhab-data/conf:/openhab/conf
      - /opt/openhab-data/userdata:/openhab/userdata
      - /opt/openhab-data/addons:/openhab/addons
      - /opt/openhab-data/logs:/openhab/logs
      - /opt/openhab-data/java:/openhab/.java
