# Openhab
version: '3'

services:

  openhab:
    image: openhab/openhab:{{ pillar.openhab.version }}
    links:
      - mosquitto
      - influxdb
    restart: always
    ports:
      - {{ pillar.static.proxy_ports.openhab_http }}:8080
    environment:
      - USER_ID={{ pillar.static.uids.master }}
      - GROUP_ID={{ pillar.static.uids.master }}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - {{ pillar.openhab.data_dir }}/conf:/openhab/conf
      - {{ pillar.openhab.data_dir }}/userdata:/openhab/userdata
      - {{ pillar.openhab.data_dir }}/addons:/openhab/addons
      - {{ pillar.openhab.data_dir }}/logs:/openhab/logs
      - {{ pillar.openhab.data_dir }}/java:/openhab/.java

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:{{ pillar.openhab.zigbee2mqtt.version }}
    links:
      - mosquitto
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - {{ pillar.openhab.zigbee2mqtt.data_dir }}:/app/data
    {% if pillar.openhab.zigbee2mqtt.device %}
    devices:
      - {{ pillar.openhab.zigbee2mqtt.device }}:{{ pillar.openhab.zigbee2mqtt.device }}
    {% endif %}

  mosquitto:
    image: eclipse-mosquitto:{{ pillar.openhab.mosquitto.version }}
    restart: always
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - {{ pillar.openhab.mosquitto.data_dir }}/config:/mosquitto/config
      - {{ pillar.openhab.mosquitto.data_dir }}/data:/mosquitto/data
      - {{ pillar.openhab.mosquitto.data_dir }}/log:/mosquitto/log

  influxdb:
    image: influxdb:{{ pillar.openhab.influxdb.version }}
    ports:
      - '8086:8086'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - {{ pillar.openhab.influxdb.data_dir }}:/var/lib/influxdb

  grafana:
    image: grafana/grafana:{{ pillar.openhab.grafana.version }}
    restart: always
    ports:
      - '{{ pillar.static.proxy_ports.openhab_grafana }}:3000'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - {{ pillar.openhab.grafana.data_dir }}:/var/lib/grafana
