#!/bin/bash -e

# Backup only machines, having tag 'backup'. Exclude all others.
# This allows to exclude test machines, which are running on the same host.

pct-vzdump-all /mnt/julia-data/backup/vz/ /mnt/julia-data/backup/vz/
