#!/bin/bash -xe

cd /mnt/julia-data/backup/vz/

# How much backups to store
VMZ_RETAIN="3"
# Included
VMZ_BACKUP="--all"
# Excluded
# 100: old home ct with broken disk: TODO: remove
VMZ_EXCLUDE="--exclude 100"

# Backup all CT and VM
vzdump $VMZ_BACKUP $VMZ_EXCLUDE -compress lzo -dumpdir $PWD/ -tmpdir $PWD/ -mailto root --maxfiles $VMZ_RETAIN
