{
 "title": "Climate",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "smarthome", "label": "Smarthome", "query": { "query": "label_values(smarthome)" } },
   { "name": "resolution", "label": "Resolution", "query": "30s, 1m, 3m, 5m, 10m, 30m, 1h" }
  ]
 },
 "panels": [
  {
   "title": "Outside",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ext_climate_temperature_value{smarthome=\"$smarthome\"}",
     "legendFormat": "Temperature"
    },
    {
     "expr": "ext_climate_humidity_value{smarthome=\"$smarthome\"}",
     "legendFormat": "Humidity"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~'.*co2.*', type=\"Number:Dimensionless\", smarthome=\"$smarthome\"}, \"label_s\", \"$1\", \"label\", \"([^ ]+).*\") * 1000000",
     "legendFormat": "{{label_s}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "label_replace({__name__!~'ext_.*', __name__=~'.*_climate_temperature_value', type='Number:Temperature', smarthome='$smarthome'}, \"label_s\", \"$1\", \"label\", \"([^ ]+).*\")",
     "legendFormat": "{{label_s}}"
    }
   ]
  },
  {
   "title": "Humudity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace({__name__!~'ext_.*', __name__=~'.*_climate_humidity_value', type='Number:Dimensionless', smarthome='$smarthome'}, \"label_s\", \"$1\", \"label\", \"([^ ]+).*\")",
     "legendFormat": "{{label_s}}"
    }
   ]
  }
 ]
}