{
 "title": "AC Power",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "smarthome", "label": "Smarthome", "query": { "query": "label_values(smarthome)" } },
   { "name": "resolution", "label": "Resolution", "query": "30s, 1m, 3m, 5m, 10m, 30m, 1h" }
  ]
 },
 "panels": [
  {
   "title": "Main voltage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace({__name__=~'^main_power_ac_voltage_.*_value', type=\"Number:ElectricPotential\", smarthome=\"$smarthome\"}, \"label_s\", \"$1\", \"label\", \".*([A-C])\")",
     "legendFormat": "{{label_s}}"
    }
   ]
  },
  {
   "title": "Main current",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace({__name__=~'^main_power_ac_current_.*_value', type=\"Number:ElectricCurrent\", smarthome=\"$smarthome\"}, \"label_s\", \"$1\", \"label\", \".*([A-C])\")",
     "legendFormat": "{{label_s}}"
    }
   ]
  },
  {
   "title": "Main power",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace({__name__=~'^main_power_ac_power_.*_value', type=\"Number:Power\", smarthome=\"$smarthome\"}, \"label_s\", \"$1\", \"label\", \".*([A-C])\")",
     "legendFormat": "{{label_s}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Frequency",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~'^main_power_ac_frequency_value', smarthome=\"$smarthome\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Total power",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~'^main_power_ac_power_value', smarthome=\"$smarthome\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Power factor",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~'^main_power_ac_power_factor_value', smarthome=\"$smarthome\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Total cosumed",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~'^main_power_ac_energy_value', smarthome=\"$smarthome\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Main voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~'^main_power_ac_voltage_.*_value', type=\"Number:ElectricPotential\", smarthome=\"$smarthome\"}, \"label_s\", \"$1\", \"label\", \".*([A-C])\")",
     "legendFormat": "{{label_s}}"
    }
   ]
  },
  {
   "title": "Main power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~'^main_power_ac_power_.*_value', type=\"Number:Power\", smarthome=\"$smarthome\"}, \"label_s\", \"$1\", \"label\", \".*([A-C])\")",
     "legendFormat": "{{label_s}}"
    }
   ]
  },
  {
   "title": "Energy used",
   "type": "bargauge",
   "description": "Energy used in selected period",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase({__name__=~'.*energy_value', __name__ !~ '^main_power_.*', type=\"Number:Energy\", smarthome=\"$smarthome\"}[$__range])",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Energy current",
   "type": "gauge",
   "description": "Energy used in selected period",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~'.*power_value', __name__ !~ '^main_power_.*', type=\"Number:Power\", smarthome=\"$smarthome\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "AC Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "{__name__=~'.*_power_value', __name__ !~ '^main_power_.*', type='Number:Power', smarthome='$smarthome'}",
     "legendFormat": "{{label}}"
    }
   ]
  }
 ]
}