{
 "title": "Heating",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "smarthome", "label": "Smarthome", "query": { "query": "label_values(smarthome)" } },
   { "name": "resolution", "label": "Resolution", "query": "30s, 1m, 3m, 5m, 10m, 30m, 1h" }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~'.*hz_temperature_sensor_value', smarthome=\"$smarthome\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Thermostat",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace({__name__=~'.*_heating_thermostat_value', smarthome=\"$smarthome\"}, \"label_s\", \"$1\", \"label\", \"([^ ]+).*\")",
     "legendFormat": "{{label_s}}"
    }
   ]
  },
  {
   "title": "Calibration",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace({__name__=~'.*_heating_local_temperature_calibration_value', smarthome=\"$smarthome\"}, \"label_s\", \"$1\", \"label\", \"([^ ]+).*\")",
     "legendFormat": "{{label_s}}"
    }
   ]
  },
  {
   "title": "Thermostat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~'.*_heating_thermostat_value', smarthome=\"$smarthome\"}, \"label_s\", \"$1\", \"label\", \"([^ ]+).*\")",
     "legendFormat": "{{label_s}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "{__name__=~'.*hz_temperature_sensor_value', smarthome=\"$smarthome\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Calibration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~'.*_heating_local_temperature_calibration_value',smarthome=\"$smarthome\"}, \"label_s\", \"$1\", \"label\", \"([^ ]+).*\")",
     "legendFormat": "{{label_s}}"
    }
   ]
  }
 ]
}