{
 "title": "VPN Julia clients",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": "vpn.b.pws,vpn.m.pws,vpn.j.pws" }
  ]
 },
 "panels": [
  {
   "title": "Client traffic",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device=~\"awg-j-.*\",instance=~\"$node\",job=\"node-exporter\"}[$__range]) + increase(node_network_transmit_bytes_total{device=~\"awg-j-.*\",instance=~\"$node\",job=\"node-exporter\"}[$__range])) by (device)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Client traffic (hourly)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device=~\"awg-j-.*\",instance=~\"$node\",job=\"node-exporter\"}[1h]) + increase(node_network_transmit_bytes_total{device=~\"awg-j-.*\",instance=~\"$node\",job=\"node-exporter\"}[1h])) by (device)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "WAN-EU traffic",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device=\"awg-wan\",instance=~\"$node\",job=\"node-exporter\"}[$__range])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "WAN month predict",
   "type": "bargauge",
   "description": "Predict volume, in % from 5Tb",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device=~\"awg-wan\",instance=~\"$node\",job=\"node-exporter\"}[30d]) / (5 * 1024^4)) by (device)",
     "legendFormat": "Monthly"
    },
    {
     "expr": "sum((increase(node_network_receive_bytes_total{device=~\"awg-wan\",instance=~\"$node\",job=\"node-exporter\"}[1d]) * 30) / (5 * 1024^4)) by (device)",
     "legendFormat": "Daily"
    }
   ]
  },
  {
   "title": "WAN-RU traffic",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device=~\"(eth-.*)\",instance=~\"$node\",job=\"node-exporter\"}[$__range])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}