#!/bin/bash

# Kill all background jobs on exit
trap 'kill $(jobs -p)' EXIT

logger -t i3-session "Lock screen"

# Start background job to turn off display after 1 minute
(sleep 10 && xset dpms force suspend) &

# Reset current layout to US
# to allow password be always-correct
xkb-switch -s 'us'

# Set Scroll lock to ON
# To indicate that we are locked (when display is sleeping)
xset led 3

# Lock screen
# Nice tool from https://github.com/yvbbrjdr/i3lock-fancy-rapid
# Random effects for blur
fancy_radius=("10" "pixel")
{#- Warning! This is a Jinja template! {{ '{#' }} - is control sequence to print #}
i3lock-fancy-rapid 20 ${fancy_radius[ $RANDOM % ${{ '{#' }}fancy_radius[@]} ]} --nofork

# Unlock done, make OFF scroll lock
xset -led 3

logger -t i3-session "Unlock screen"
