#!/bin/bash

xrandr --output eDP-1 --off
xrandr --output DP-1-1 --scale 1.0x1.0 --mode 3840x2160 --dpi 138 --pos 0x0 --primary
xrandr --output DP-1-2 --scale 1.0x1.0 --mode 3840x2160 --dpi 138 --pos 3840x0
