#!/bin/bash

DEVICES=$(bluetoothctl devices Connected | grep -P '(Soundcore|BES_BLE)' | grep -o "[[:xdigit:]:]\{8,17\}")

if [[ -z $DEVICES ]]; then
    echo "No soundcore devices found"
    echo "Check that you have device connected with containing 'Soundcore'"
    echo "Devices list command: bluetoothctl devices"
    exit 1
fi

for device in $DEVICES; do
    echo "Soundcore device: $device"

    bt-force-profile a2dp-sink-sbc_xq $device
done
