#!/bin/bash

#!/bin/bash
for device in $(bluetoothctl devices | grep Soundcore | grep -o "[[:xdigit:]:]\{8,17\}"); do
    echo "Soundcore device: $device"

    AnkerSoundcoreAPI.py -AmbientSound ANC $device
done

