#!/bin/bash

# Reset current layout to default (US)
# to allow promt be always-correct
swaymsg input type:keyboard xkb_switch_layout 0

sudo brightnessctl --device='*::scrolllock' set 1

PREFIX=/opt/swaylock-fancy /opt/swaylock-fancy/swaylock-fancy --pixelate

sudo brightnessctl --device='*::scrolllock' set 0
