#!/bin/bash -xe

while true; do
    sleep 180

    WINDOWS=$(xdotool search --onlyvisible --name "Microsoft Teams")
    ACTIVE_WINDOW=$(xdotool getactivewindow)

    if [[ -z "$WINDOWS" ]] ; then
        echo "No Teams found"
        continue
    fi

    if [[ -z "$ACTIVE_WINDOW" ]] || (echo "$WINDOWS" | grep "$ACTIVE_WINDOW") ; then
        echo "One of windows has focus already"
        continue
    fi

    # Save current kb layout
    LAY=$(xkb-switch)

    for w in $WINDOWS; do
        xdotool windowactivate --sync $w key Shift
    done
    # Revert layout
    xkb-switch -s "$LAY"
    xdotool windowactivate "$ACTIVE_WINDOW"
done
