#!/bin/bash
# This script watches keyboard switches and update led accordingly
# originally, X11 toggles only led on one keyboard, we need to multicast change

while true; do
    # Wait for change
    xkb-switch -w
    if xkb-switch -p | grep -q "us"; then
        xset -led 1
    else
        xset led 1
    fi
done
