version: '3'

services:
  jenkins:
    container_name: jenkins-app
    image: jenkins/jenkins:{{ pillar.jenkins.version }}
    ports:
      - {{ pillar.static.proxy_ports.jenkins_http }}:8080
      - {{ pillar.static.proxy_ports.jenkins_agent }}:{{ pillar.static.proxy_ports.jenkins_agent }}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - {{ pillar.jenkins.data_dir }}:/var/jenkins_home
    restart: always
