#!/usr/bin/env python3
"""
Local check to ensure last backup date
"""

import os
import datetime

marker_file = '/var/local/ext-backup'

mtime = os.path.getmtime(marker_file)
mtime = datetime.datetime.fromtimestamp(mtime)

delta_days = (datetime.datetime.today() - mtime).days

print(f"P \"External backup age\" count={delta_days};2;5 Days from last backup")
