# Openhab
version: '3'

services:

  openhab:
    container_name: {{ pillar.openhab.id }}
    build: .
    network_mode: host
    restart: always
    ports:
      - '8080:8080'
    environment:
      - USER_ID={{ pillar.static.uids.master }}
      - GROUP_ID={{ pillar.static.uids.master }}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - {{ pillar.openhab.data_dir }}/conf:/openhab/conf
      - {{ pillar.openhab.data_dir }}/userdata:/openhab/userdata
      - {{ pillar.openhab.data_dir }}/addons:/openhab/addons
      - {{ pillar.openhab.data_dir }}/java:/openhab/.java

  zigbee2mqtt:
    container_name: {{ pillar.openhab.zigbee2mqtt.id }}
    image: koenkk/zigbee2mqtt:{{ pillar.openhab.zigbee2mqtt.version }}
    restart: always
    ports:
      - '127.0.0.1:3001:3001'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - {{ pillar.openhab.zigbee2mqtt.data_dir }}:/app/data
    {% if pillar.openhab.zigbee2mqtt.device %}
    devices:
      - {{ pillar.openhab.zigbee2mqtt.device }}:/dev/ttyUSB-Z-Stack
    {% endif %}

  mosquitto:
    container_name: {{ pillar.openhab.mosquitto.id }}
    image: eclipse-mosquitto:{{ pillar.openhab.mosquitto.version }}
    restart: always
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - {{ pillar.openhab.mosquitto.data_dir }}/config:/mosquitto/config
      - {{ pillar.openhab.mosquitto.data_dir }}/data:/mosquitto/data
      - {{ pillar.openhab.mosquitto.data_dir }}/log:/mosquitto/log

  {%- if pillar.openhab.tuyamqtt.id %}
  tuya-mqtt:
    container_name: {{ pillar.openhab.tuyamqtt.id }}
    image: gugabguerra/tuya-mqtt:{{ pillar.openhab.tuyamqtt.version }}
    restart: always
    environment:
      - DEBUG=tuya-mqtt:*
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - {{ pillar.openhab.tuyamqtt.data_dir }}/config.json:/app/config.json:ro
      - {{ pillar.openhab.tuyamqtt.data_dir }}/devices.conf:/app/devices.conf:ro
  {%- endif %}

  influxdb:
    container_name: {{ pillar.openhab.influxdb.id }}
    image: influxdb:{{ pillar.openhab.influxdb.version }}
    restart: always
    ports:
      - '8086:8086'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - {{ pillar.openhab.influxdb.data_dir }}:/var/lib/influxdb

{% if pillar.openhab.grafana.id %}
  grafana:
    container_name: {{ pillar.openhab.grafana.id }}
    image: grafana/grafana:{{ pillar.openhab.grafana.version }}
    restart: always
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - "GF_PATHS_CONFIG=/var/lib/grafana/grafana.ini"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - {{ pillar.openhab.grafana.data_dir }}:/var/lib/grafana
{% endif %}

{% if pillar.openhab.yandex2mqtt.id %}
  yandex2mqtt:
    container_name: {{ pillar.openhab.yandex2mqtt.id }}
    image: petrows/yandex2mqtt:{{ pillar.openhab.yandex2mqtt.version }}
    restart: always
    ports:
      - '4001:4001'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /srv/openhab-data/conf/services/yandex2mqtt.js:/opt/yandex2mqtt/config.js:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
{% endif %}
