{
 "title": "VPN Julia clients",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": "vpn.b.pws,vpn.m.pws,vpn.j.pws" },
   { "name": "resolution", "label": "Resolution", "query": "30s, 1m, 3m, 5m, 10m, 30m, 1h" },
   {
    "name": "user",
    "label": "Пользователь",
    "query": {
     "query": "label_values(wg_peer_transfer_rx_bytes,interface_comment)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Client traffic",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\nsort_desc(\n  sum by (interface_comment) (\n    increase(wg_peer_transfer_rx_bytes{ instance=~\"$node\", interface!=\"awg-wan\", interface_comment!=\"\" }[$__range])\n    +\n    increase(wg_peer_transfer_tx_bytes{ instance=~\"$node\", interface!=\"awg-wan\", interface_comment!=\"\" }[$__range])\n  )\n)\n",
     "legendFormat": "{{interface_comment}}"
    }
   ]
  },
  {
   "title": "Client traffic (hourly)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(wg_peer_transfer_rx_bytes{ instance=~\"$node\", interface!=\"awg-wan\", interface_comment!=\"\", interface_comment=~\"$user\" }) + increase(wg_peer_transfer_tx_bytes{ instance=~\"$node\", interface!=\"awg-wan\", interface_comment!=\"\", interface_comment=~\"$user\" })) by (interface_comment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAN-EU traffic",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device=\"awg-wan\",instance=~\"$node\",job=\"node-exporter\"}[$__range])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "WAN month predict",
   "type": "bargauge",
   "description": "Predict volume, in % from 5Tb",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device=~\"awg-wan\",instance=~\"$node\",job=\"node-exporter\"}[30d]) / (5 * 1024^4)) by (device)",
     "legendFormat": "Monthly"
    },
    {
     "expr": "sum((increase(node_network_receive_bytes_total{device=~\"awg-wan\",instance=~\"$node\",job=\"node-exporter\"}[1d]) * 30) / (5 * 1024^4)) by (device)",
     "legendFormat": "Daily"
    }
   ]
  },
  {
   "title": "WAN-RU traffic",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device=~\"(eth-.*)\",instance=~\"$node\",job=\"node-exporter\"}[$__range])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Peers traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(wg_peer_transfer_rx_bytes{ instance=~\"$node\", interface_comment!=\"\", interface_comment=~\"$user\", interface!=\"awg-wan\" } + wg_peer_transfer_tx_bytes{ instance=~\"$node\", interface_comment!=\"\", interface_comment=~\"$user\", interface!=\"awg-wan\" })) by (comment, interface_comment)",
     "legendFormat": "{{interface_comment}} / {{comment}}"
    }
   ]
  },
  {
   "title": "Traffic per node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(wg_peer_transfer_rx_bytes{ interface_comment!=\"\", interface_comment=~\"$user\", interface!=\"awg-wan\" } + wg_peer_transfer_tx_bytes{ interface_comment!=\"\", interface_comment=~\"$user\", interface!=\"awg-wan\" })) by (instance, comment)",
     "legendFormat": "{{comment}} / {{instance}}"
    }
   ]
  },
  {
   "title": "Latest handshake",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - max by (interface_comment, comment, instance)(max_over_time(wg_peer_latest_handshake_timestamp{interface_comment=~\"$user\", instance=~\"$node\"}[30d]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}