# Define global systemd env for UI apps
QT_QPA_PLATFORMTHEME=kde
XDG_CURRENT_DESKTOP=KDE
QT_WAYLAND_DISABLE_WINDOWDECORATION=1  # use Sway's borders, not Qt's
GTK_THEME=Breeze-Dark
GTK_ICON_THEME=breeze-dark
