# Define user-path
PATH=${PATH}:${HOME}/bin
# Define global systemd env for UI apps
QT_QPA_PLATFORMTHEME=kde
# use Sway's borders, not Qt's
QT_WAYLAND_DISABLE_WINDOWDECORATION=1
GTK_THEME=Breeze-Dark
GTK_ICON_THEME=Papirus-Dark
