# MediaWiki with MariaDB
version: '2'

services:
  mediawiki:
    image: mediawiki
    restart: always
    ports:
      - 7003:80
    links:
      - database
    volumes:
      - /opt/wiki/images:/var/www/html/images
      # After initial setup, download LocalSettings.php to the same directory as
      # this yaml and uncomment the following line and use compose to restart
      # the mediawiki service
      {% if salt['file.exists']('/opt/wiki/LocalSettings.php') %}
      - /opt/wiki/LocalSettings.php:/var/www/html/LocalSettings.php
      {% endif %}
  database:
    image: mariadb
    restart: always
    environment:
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
