{%- set cfg = salt['pillar.get']('proxy_vhosts:'+service_id, {}) -%}
{%- set default_revision = salt['pillar.get']('php-docker:defaults:container_revision', {}) %}
{%- set default_interface = (salt['network.default_route']('inet')|first)['interface']|default('none') %}
{%- set default_ip = salt['network.interface_ip'](default_interface) %}
{%- set data_root = '/srv/' + service_id -%}
{%- set db = cfg.php.db | default({}) -%}
{%- set container_revision = cfg.php.container_revision | default(default_revision) -%}
version: '3'

services:
  app:
    container_name: {{ service_id }}-fpm
    image: petrows/saltstack:php-fpm-{{ cfg.php.version }}-{{ container_revision }}
    user: '{{ cfg.php.user }}'
    ports:
      - '{{ cfg.port }}:9000'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /opt/{{ service_id }}/php.ini:/usr/local/etc/php/conf.d/vhost.ini:ro
      - {{ cfg.root }}/web:/var/www/html
    restart: always
    extra_hosts:
    {%- for _, all_cfg in salt['pillar.get']('proxy_vhosts', {}).items() %}
      - "{{ all_cfg.domain }}:{{ default_ip }}"
    {%- endfor %}
{%- if db %}
  db:
    container_name: {{ service_id }}-db
    image: {{ db.image }}
    user: '{{ cfg.php.user }}'
    environment:
    {%- if db.type == 'mariadb' %}
      MYSQL_DATABASE: '{{ db.dbname }}'
      MYSQL_USER: '{{ salt['pillar.get']('pws_secrets:' + db.credentials + ':username' ) }}'
      MYSQL_PASSWORD: '{{ salt['pillar.get']('pws_secrets:' + db.credentials + ':password' ) }}'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    {%- endif %}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      {%- if db.type == 'mariadb' %}
      - {{ data_root }}/db:/var/lib/mysql
      {%- endif %}
    restart: always
{%- endif %}
