{%- set cfg = salt['pillar.get']('proxy_vhosts:'+service_id, {}) -%}
{%- set data_root = '/srv/' + service_id -%}
{%- set db = cfg.php.db | default({}) -%}
version: '3'

services:
  app:
    container_name: {{ service_id }}-fpm
    image: php:{{ cfg.php.version }}-fpm
    user: {{ cfg.php.user }}
    ports:
      - '{{ cfg.port }}:9000'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /opt/{{ service_id }}/php.ini:/usr/local/etc/php/conf.d/vhost.ini:ro
      - {{ cfg.root }}/web:/var/www/html
    restart: always
{%- if db %}
  db:
    container_name: {{ service_id }}-db
    image: {{ db.image }}
    user: {{ cfg.php.user }}
    environment:
    {%- if db.type == 'mariadb' %}
      MYSQL_DATABASE: {{ db.dbname }}
      MYSQL_USER: {{ salt['pillar.get']('pws_secrets:' + db.credentials + ':username' ) }}
      MYSQL_PASSWORD: {{ salt['pillar.get']('pws_secrets:' + db.credentials + ':password' ) }}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    {%- endif %}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      {%- if db.type == 'mariadb' %}
      - {{ data_root }}/db:/var/lib/mysql
      {%- endif %}
    restart: always
{%- endif %}
